New branch2
takashi-ueki/Mybatis-work0920 pull request #3
Opened 2022-10-03 19:59 UTC by takashi-ueki

クエリ文字列を使って、DBに登録されている収支データから、各カテゴリの収支データをレスポンスとして返せるようにしました。
- # 出力結果

- ## カテゴリがTravelのデータ
<img width="419" alt="image" src="https://user-images.githubusercontent.com/107293004/193666881-def59b98-5de6-4b8d-994a-38493ce8b7df.png">

- ## カテゴリがFoodのデータ
<img width="422" alt="image" src="https://user-images.githubusercontent.com/107293004/193666997-bebb0dd2-499b-41d2-afca-ba6e793bb298.png">

- ## クエリ文字列を使わない場合
<img width="415" alt="image" src="https://user-images.githubusercontent.com/107293004/193667382-688c1236-2c03-41d5-badb-51f99e942865.png">

2022-10-04 02:42 UTC, YudaiNoda3576 requested changes
コメントしています

2022-10-04 02:42 UTC, YudaiNoda3576 commented on src/main/java/com/training/Mybatiswork0920/controller/HouseholdAccountController.java
> +    public ResponseEntity<Map<String, String>> update(@RequestBody CreateForm form, @PathVariable("id") int id) {
一つ前のPRの差分が反映されていると思うので、こちらは反映されないように修正してみてください〜

2022-10-04 02:42 UTC, YudaiNoda3576 commented on src/main/java/com/training/Mybatiswork0920/controller/HouseholdAccountController.java
> +                .filter(c -> c.getCategory().contains(category))
filterを使用されているんですね！（面白い）
DBからデータを引いてくる時点で、クエリに完全一致するデータのみを取得するように修正してみてください！

2022-10-04 20:13 UTC, takashi-ueki commented on src/main/java/com/training/Mybatiswork0920/controller/HouseholdAccountController.java
> +                .filter(c -> c.getCategory().contains(category))
不要なデータを引いてきて、さらにフィルタをしているというロスがあるということですね。ありがとうございます。挑戦してみます。

2022-10-04 21:30 UTC, takashi-ueki commented on src/main/java/com/training/Mybatiswork0920/controller/HouseholdAccountController.java
> +    public ResponseEntity<Map<String, String>> update(@RequestBody CreateForm form, @PathVariable("id") int id) {
ご指摘ありがとうございます。
File Change に反映されていない状態になったと思います。

2022-10-05 04:31 UTC, YudaiNoda3576 requested changes
コメントしています！

2022-10-05 04:31 UTC, YudaiNoda3576 commented on src/main/java/com/training/Mybatiswork0920/controller/HouseholdAccountController.java
> +        if (category == null) {
リクエストパラメータが必須ではないが、nullなら有無を言わさずreturnするという仕様に違和感を感じるのですがいかがでしょうか？？
パラメータが存在しなければ全件取得した結果を返すのが正のような気がします🤔

2022-10-05 21:08 UTC, YudaiNoda3576 reviewed
すみません追加で気になったことがあったのでコメントしています〜

2022-10-05 21:08 UTC, YudaiNoda3576 commented on src/main/java/com/training/Mybatiswork0920/controller/HouseholdAccountController.java
>      public static class CreateForm {
ここは今回のPRの範囲ではないと思うんですが、Classをネストしているのは何ででしょうか・・・？

2022-10-12 09:35 UTC, YudaiNoda3576 requested changes
コメントしております！
今後のために何ですが、レビュー後はPR上のコメントに返信する形でコミットのリンクなどを貼って頂けますとレビューが捗ります！（どの変更がどの指摘に対するものか把握しづらい＆時間が経つと指摘内容そのものを忘れてしまうため）

2022-10-12 09:35 UTC, YudaiNoda3576 commented on src/main/java/com/training/Mybatiswork0920/controller/HouseholdAccountController.java
> +    public List<HouseholdAccountResponse> getAccountsByCategory(@RequestParam(name = "category", defaultValue = "") String category) {
`defaultValue` に空文字を設定いているため、SQLが実行されるときは常に下記の条件は`true`にならないでしょうか？？

```
 <if test="category !=null">
       category = #{category}
  </if>
```

2022-10-12 09:35 UTC, YudaiNoda3576 commented on src/main/java/com/training/Mybatiswork0920/controller/HouseholdAccountController.java
>      @GetMapping("/accounts")
よくあるURLでいくとここは`accounts/search?name=hogehoge`みたいな形が良いのかなと思いました！

2022-10-12 09:35 UTC, YudaiNoda3576 commented on src/main/java/com/training/Mybatiswork0920/controller/HouseholdAccountController.java
> +    @GetMapping("/accounts/all")
ここのPATHは`accounts`でも良いような気がしました！

2022-10-14 03:54 UTC, YudaiNoda3576 approved these changes
コメントしています！

2022-10-14 03:54 UTC, YudaiNoda3576 commented on src/main/resources/com/training/Mybatiswork0920/mapper/HouseholdAccountMapper.xml
> +            category = #{category}
これをするとパラメータが空の時はどうなりますか？？
僕の指摘の意図としては、ControllerクラスではパラメータにDefaultValueとして""が指定されているため、以下の処理が必ずtrueになるのではないかと思った次第です！
 ```
 <if test="category !=null">
                category = #{category}
            </if>
```

2022-10-14 03:56 UTC, YudaiNoda3576 commented on src/main/java/com/training/Mybatiswork0920/controller/HouseholdAccountController.java
>      public static class CreateForm {
@takashi-ueki 
この件ってどうなりましたか？？

2022-10-19 20:40 UTC, YudaiNoda3576 requested changes
コメントしています〜！

2022-10-19 20:40 UTC, YudaiNoda3576 commented on src/main/java/com/training/Mybatiswork0920/Form/CreateForm.java
> +public class CreateForm {
`create`と`update`というのはアクションで、`Form`の中身を左右するものではないと思います！
なので命名を変更して（これは従業員 の情報を管理するとかですかね？ならばEmployeeFormとかな気がします🤔）、一つのFormクラスに集約してしまっても問題ないように思います！

もし二つに分けた理由がありましたら共有いただきたいです！

2022-10-21 03:13 UTC, YudaiNoda3576 approved these changes
There is both a cypress.config.ts and a cypress.json file at the location below:

/Users/yudai/Projects/NHK_Lab/aw-editorialhands/e2e

Cypress no longer supports cypress.json, please remove it from your project.

2022-10-21 04:38 UTC, merged